language: node_js
node_js:
  - "10"

env:
  PATH=$PATH:$HOME/.local/bin
  S3_BUCKET_NAME_TEST="wallet.testnet.crypto-bridge.org"
  S3_BUCKET_NAME_STAGE="wallet.stage.crypto-bridge.org"

cache:
  directories:
    - "node_modules"
    - "build"

install:
  - pip install --user awscli

stages:
  - name: build-testnet
    if: branch = develop
  - name: deploy-testnet
    if: branch = develop

  - name: build-stage
    if: branch = master
  - name: deploy-stage
    if: branch = master

jobs:
  include:
    # - stage: lint
    #   script:
    #     - npm install
    #     - npm run lint
    - stage: build-testnet
      script:
        - npm install
        - npm run build-testnet
    - stage: deploy-testnet
      script:
        - ls -la ./build/dist/
        - aws s3 sync ./build/dist/ s3://$S3_BUCKET_NAME_TEST/ --delete

    - stage: build-stage
      script:
        - npm install
        - npm run build
    - stage: deploy-stage
      script:
        - ls -la ./build/dist/
        - aws s3 sync ./build/dist/ s3://$S3_BUCKET_NAME_STAGE/ --delete
