language: node_js
node_js:
  - "10"

env:
  PATH=$PATH:$HOME/.local/bin

cache:
  directories:
    - "node_modules"
    - "build"

install:
  - pip install --user awscli

jobs:
  include:
    - stage: build-testnet
      on:
        branch: develop
        condition: $TRAVIS_TAG = ""
      script:
        - npm install
        - npm run build-testnet
    - stage: deploy-testnet
      on:
        branch: develop
        condition: $TRAVIS_TAG = ""
      script:
        - ls -la ./build/dist/
        - export AWS_ACCESS_KEY_ID=$TEST_AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$TEST_AWS_SECRET_ACCESS_KEY
        - aws s3 sync ./build/dist/ s3://wallet.testnet.crypto-bridge.org/ --delete

    - stage: build-stage
      on:
        branch: master
        condition: $TRAVIS_TAG = ""
      script:
        - npm install
        - npm run build
    - stage: deploy-stage
      on:
        branch: master
        condition: $TRAVIS_TAG = ""
      script:
        - ls -la ./build/dist/
        - export AWS_ACCESS_KEY_ID=$STAGE_AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$STAGE_AWS_SECRET_ACCESS_KEY
        - aws s3 sync ./build/dist/ s3://wallet.stage.crypto-bridge.org/ --delete

    - stage: build-preview
      on:
        all_branches: true
        condition: $TRAVIS_TAG =~ ^v\d+\.\d+(\.\d+)?$
      script:
        - npm install
        - npm run build
    - stage: deploy-preview
      on:
        all_branches: true
        condition: $TRAVIS_TAG =~ ^v\d+\.\d+(\.\d+)?$
      script:
        - ls -la ./build/dist/
        - export AWS_ACCESS_KEY_ID=$PREVIEW_AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$PREVIEW_AWS_SECRET_ACCESS_KEY
        - aws s3 sync ./build/dist/ s3://wallet.preview.crypto-bridge.org/ --delete
